### ISSUE TITLE
Downlink Issue

### ISSUE THREAD

**Issue by rohitkumar5293** [Lora-net/LoRaMac-node#329] opened 2017-09-25 05:56 UTC
Hi, 

I am newbie to this technology. I have ported this complete LoRaWAN stack for my MCU using SX1276 transceiver via SPI. I am able to do uplink transmission properly but unable to do schedule  downlink. Hence my MCU doesn't contain RTC so i opt out RTC part. Please suggest how to do schedule downlink.   I am using ABP mode only.

**Comment by djaeckle** [comment] 2017-10-09 07:08
Hi rohitkumar5293,

you need an accurate timer to schedule the downlink windows. If you say you removed the RTC implementation you need another timer to do the job.

**Comment by rohitkumar5293** [comment] 2017-10-10 08:51
Hi Djaeckle,

As you quote above that RTC is necessary for schedule downlink, now i am implementing RTC complete. Now 1 more problem which i am facing is DIO0 pin. DIO0 pin is responsible for making interrupt between TXDONE and RXDONE. But in my case i am implementing DIO0 pin to make interrupt but i am unable to get downlink.

**Comment by eric780711** [comment] 2018-01-03 09:01
Hi rohitkumar5293
  I have the same problem, do you have a solution?

**Comment by mluis1** [comment] 2018-01-26 14:52
Have you found a solution for this issue?

Most certainly the issue is coming from the porting process.

Can we close the issue?

**Closed** 2018-02-05 13:26 UTC
Labels: question
