### ISSUE TITLE
CFList issue with FRAME_TYPE_JOIN_ACCEPT

### ISSUE THREAD

**Issue by Mobiak** [Lora-net/LoRaMac-node#48] opened 2016-02-25 16:48 UTC
Device fail to add the CFList transmitted in a join_accept frame.

When joining on OTA and getting a join_accept, the device will execute function LoRaMacChannelAdd( i, param ) to add incoming channels. This function start with few checks and fail to succeed this one :

    if( ( LoRaMacState & MAC_TX_RUNNING ) == MAC_TX_RUNNING )
    {
        return LORAMAC_STATUS_BUSY;
    }

The LoRaMacState is MAC_TX_RUNNING because it's sending join_request and getting an join_accept.
The flag can not be cleared before as it is running. Is it possible to modify this check?

**Comment by mluis1** [comment] 2016-02-25 17:22
Duplicate of Issue #43

**Comment by Mobiak** [comment] 2016-02-25 19:02
My bad on this one, forgot the previous posts and didn't check.

**Closed** 2016-03-11 15:00 UTC
Labels: duplicate
